[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:pass"
  ]

[http.routers.api]
  rule = "Host(`DOMAIN`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
