###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
# Change user: and User, password, email
users:
  user:
    displayname: "User"
    password: "password"
    email: youremail@domain.com
    groups:
      - admins
      - dev